version: '2.1'

services:
  spring-eureka-server:
    build: spring-eureka-server/
    depends_on:
      config-server:
        condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-spring-eureka-server
    hostname: localhost
    ports:
      - 8761:8761
    healthcheck:
      test: "exit 0"

  config-server:
    build: config-server/
    restart: always
    network_mode: "host"
    image: demo-config-server
    hostname: localhost
    ports:
      - 8888:8888
    healthcheck:
      test: "exit 0"

  spring-boot-zuulgateway:
    build: spring-boot-zuulgateway/
    depends_on:
      config-server:
        condition: service_healthy
      spring-eureka-server:
        condition: service_healthy
      movie-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-spring-boot-zuulgateway
    hostname: localhost
    ports:
      - 8080:8080
    healthcheck:
      test: "exit 0"

  movie-service:
    build: movie-service/
    image: demo-movie-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8762:8762
    depends_on:
      config-server:
        condition: service_healthy
      spring-eureka-server:
        condition: service_healthy
    healthcheck:
      test: "exit 0"

  user-service:
    build: user-service/
    image: demo-user-service
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 9098:9098
    depends_on:
      config-server:
        condition: service_healthy
      spring-eureka-server:
        condition: service_healthy
    healthcheck:
      test: "exit 0"

